### ISSUE TITLE
Second chat window tab wont fade upon login

### ISSUE THREAD

**Issue by Xarano-GIT** [ls-/ls_Glass#37]
Hi, Everything about the addon works super well except for one thing i've noticed.

Context, I have the main chat window (General, combat log, Etc_ and then have a seperate chat window for loot only.
When I login, the chat tab for the Loot window will not fade out and will remain on screen forever, until I click the tab upon which it will fade away fully.

Any way this could be fixed to fade fully on login?

Thanks!

**Comment by ls-** [comment]
Hi, the issue is fixed in the version for TWW. Half the addon code was rewritten which also inadvertently fixed the issue along the way 😅

![fading_on_login](https://github.com/user-attachments/assets/7b1f461b-6ec3-4740-8b79-1b5322e4fdcb)

Just wait for a week and it'll be fine.

**Comment by Xarano-GIT** [comment]
Heya LS,

Sorry to bring this up again!
Overall the new version is great and works really well, so thank you for your hard work on that.

I've found that the issue with the second chat window tab not fading can sometimes occur when hearthstoning, using the vulpera back to camp ability or using portals.

It doesn't seem to happen every time, but I often notice the tab has remained after doing one of the above which involve a loading screen.

Its not a huge deal, just something I noticed.

**Comment by ls-** [comment]
A few days ago I noticed an odd behaviour when the dock (tabs + buttons) wouldn't fade as expected, but it's fixed in [this commit](https://github.com/ls-/ls_Glass/commit/594e0063f91419b78e6d5f0e425ba22ed5f8790d). So it prob will be fixed in today's update... Probably 🤔

**Comment by Xarano-GIT** [comment]
Lovely thank you! I'll update when available and if you don't hear anything from me then it's probably fixed!

**Comment by Xarano-GIT** [comment]
Unfortunately seems like it still occurs when portaling and other loading screen activities

**Comment by ls-** [comment]
Hmm... I'll look into it, but not now, I bit busy with real life stuff 😵

**Comment by Xarano-GIT** [comment]
Thank you LS, I appreciate it!

If it helps, I have found a guaranteed way to trigger the issue.

I booted the game up fresh and logged into my character.
Without touching the chat frame or anything, I used the Vulpera racial "return to camp" which ported me away.

After the loading screen, the second tab was present but not fully faded.

Hopefully this provides you with a repeatable method :)

**Comment by ls-** [comment]
Yeah, I realised what's going on after you mentioned loading screens earlier. What's happening is that, I can't truly control dock fading on my end due to how it's implemented on blizz end, like, if I try to override that behaviour I'll literally break the whole UI when you're in combat 😵

So I let Blizz code do it thing, for instance, it fades out the tabs after a certain period of time, but it only fades them out to like 0.25 alpha, and on my end I do the rest and fade them out completely. But what happens when you go through a loading screen is that Blizz code resets stuffs, but my code still thinks that it's fully faded out.

To fix that I'll just need to reset the state on my end as well, it's not hard, I'm just busy atm.
